name: uts_mobprog_kelompok_2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/utiwi-logo.png
   - assets/images/utiwi-splash-logo.png
   - assets/images/onboarding/onboarding1.png
   - assets/images/onboarding/onboarding2.png
   - assets/images/onboarding/onboarding3.png

  fonts:
    - family: Handjet
      fonts:
        - asset: fonts/Handjet-Regular.ttf
        - asset: fonts/Handjet-Bold.ttf
          weight: 700
